### ISSUE TITLE
Add day of the year

### ISSUE THREAD

**Issue by bmitch** [bmitch/relogio#2]
Example "It's day 30 of 365... there are 335 days of the year left"

**Comment by ntrupin** [comment]
I’d like to pick this issue up. I’ve already made a fork and began work on it.

**Comment by bmitch** [comment]
Awesome, by all means !

**Comment by ntrupin** [comment]
@bmitch I've added the day of the year, and submitted a pull request.

https://github.com/bmitch/relogio/pull/6

**Comment by bmitch** [comment]
Fixed in #6
